### ISSUE TITLE
[Feat] 관리자뷰 홈화면 구현

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthonUniv-seoultech/PROJECT_TEAM_APP_FE2#11]
## ✅ Description

관리자뷰 홈화면 - 강의실 현황 화면 구현

## ✔️ TODO
- [ ] 강의실 현황 화면 구현
- [ ] 필터 기능 구현
- [ ] 강의실 세부 현황 화면 구현
- [ ] 예약 거절/예약 취소 모달 구현
