### ISSUE TITLE
[Feat] 관리자뷰 예약 관리 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthonUniv-seoultech/PROJECT_TEAM_APP_FE2#16]
## ✅ Description

관리자뷰 예약 관리 화면 구성

## ✔️ TODO
- [ ] 관리자뷰 예약 대기 화면 구성
- [ ] 관리자뷰 예약 승인 화면 구성
- [ ] 관리자뷰 예약 거절 화면 구성
