### ISSUE TITLE
[Feat] 관리자뷰 강의실 예약 화면 구성

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthonUniv-seoultech/PROJECT_TEAM_APP_FE2#18]
## ✅ Description

관리자뷰 강의실 예약 화면 구성

## ✔️ TODO
- [ ] 관리자뷰 강의실 예약 - 일반 화면 구성
- [ ] 관리자뷰 강의실 예약 - 기간 화면 구성
- [ ] 관리자뷰 강의실 예약 - 반복 화면 구성
