### ISSUE TITLE
[Feat] 관리자뷰 API 연동 기능 구현

### ISSUE THREAD

**Issue by PIYUJIN** [9oormthonUniv-seoultech/PROJECT_TEAM_APP_FE2#20]
## ✅ Description

관리자뷰 API 연동 기능 구현

## ✔️ TODO
- [ ] 관리자뷰 강의실 현황 API 연동 기능 구현
- [ ] 관리자뷰 예약 관리 API 연동 기능 구현
- [ ] 관리자뷰 강의실 예약 API 연동 기능 구현
